# Site settings
author: jose cortez
title: CORTEZ'S BLOG
header-img: img/home-bg.png
email: cortezluisjose@gmail.com
copyright_name: jose cortez
description: > # this means to ignore newlines until "baseurl:"
  BOOK-PROJECT
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  elcocinero1982

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
